### ISSUE TITLE
Not able to run ctakes-web-client war deployment in tomcat

### ISSUE THREAD

**Issue by gandhirajan** [healthnlp/examples#4]
I downloaded the ctakes-web-client from this git hub repo and built ctakes-web-client.war using maven build. Then I downloaded this web app in tomcat. The deployment was successful and was  able to access the index page without any errors. But when I click on submit button after enter text in textbox, it gives the following error: 

**javax.servlet.ServletException: org.apache.uima.resource.ResourceInitializationException: Initialization of annotator class "org.apache.ctakes.dictionary.lookup2.ae.DefaultJCasTermAnnotator" failed.  (Descriptor: <unknown>)
	org.apache.ctakes.web.client.servlet.DemoServlet.init(DemoServlet.java:70)
	javax.servlet.GenericServlet.init(GenericServlet.java:158)**

I m using 64 bit Java 1.8.0_131-b11.  

Please help me out in resolving this issue.Thanks in advance.

**Comment by gandhirajan** [comment]
Can anyone help me out on this?

**Comment by gandhirajan** [comment]
Finally managed to resolve this issue and its related to HSQL InMemory DB with tomcat deployment.

**Comment by Zaky7** [comment]
Could you elaborate how you solved this problem. I am also getting same problem when I am running a ctakes.war on my docker with 64 bit  Java 1.8.0_151 , tomcat 8.

**Comment by gandhirajan** [comment]
I moved away from HSQL db to MySQL. But if u r still using HSQL, just check all HSQL related files are in place in exploded war
