### ISSUE TITLE
help need to run this 

### ISSUE THREAD

**Issue by swagat123** [healthnlp/examples#7]
Hi all, 

I am quite new to this ctakes also to java. i want to run this ctakes-web-client in tom cat apache. do i need to build this in eclpise? i use the command mvn package at command prompt to create a .war file and copied that war file to tampcat -> webapp. try to run tomcat but i got error like

javax.servlet.ServletException: org.apache.uima.resource.ResourceInitializationException: Initialization of annotator class "org.apache.ctakes.dictionary.lookup2.ae.DefaultJCasTermAnnotator" failed.  (Descriptor: <unknown>)

Root Cause

org.apache.uima.resource.ResourceInitializationException: Initialization of annotator class "org.apache.ctakes.dictionary.lookup2.ae.DefaultJCasTermAnnotator" failed.  (Descriptor: <unknown>)
	

i am using tomact 7.0, eclipse neon jav ide for EE.

Regards
Swagat

**Comment by gandhirajan** [comment]
Try running it using inbuilt jetty server in the project. I faced some problem deploying it in tomcat due to permission issue of hsql db creation inside tomcat. Hence I moved to MySQL server + tomcat combination

**Comment by swagat123** [comment]
Thank you @gandhirajan . I installed this jetty plugin and ran this. It worked.
